export const Teachers = [
  {
    name: "মোঃ হাসিবুল ইসলাম (শান্ত)",
    subject: "মার্কেটিং বিভাগ, ব্যবসায় শিক্ষা অনুষদ",
    qualification: "ঢাকা বিশ্ববিদ্যালয়",
    image: "/images/shanto.jpg",
    bio: "৬ বছর শিক্ষকতার অভিজ্ঞতা",
  },
  {
    name: "এফরান হোসেন রিয়াজ",
    subject: "ইলেক্ট্রিক্যাল এন্ড ইলেক্ট্রনিক্স ইঞ্জিনিয়ারিং (EEE)",
    qualification: "ইউনিভার্সিটি অফ স্কলার্স",
    image: "/images/reaz.jpg",
    bio: "৬ বছর শিক্ষকতার অভিজ্ঞতা",
  },
  {
    name: "ফয়সাল আহমেদ",
    subject: "কম্পিউটার সায়েন্স এন্ড ইঞ্জিনিয়ারিং (CSE)",
    qualification: "ইস্ট ওয়েস্ট ইউনিভার্সিটি",
    image: "/images/faisal.jpg",
    bio: "৫ বছর শিক্ষকতার অভিজ্ঞতা",
  },
  {
    name: "সাদাত হোসেন রানা",
    subject: "রসায়ন বিভাগ, বিজ্ঞান অনুষদ",
    qualification: "ঢাকা বিশ্ববিদ্যালয়",
    image: "/images/rana.jpg",
    bio: "৩ বছর শিক্ষকতার অভিজ্ঞতা",
  },
  {
    name: "সাজেদুল হক শুভ",
    subject: "একাউন্টিং বিভাগ, ব্যবসায় শিক্ষা অনুষদ",
    qualification: "ঢাকা বিশ্ববিদ্যালয়",
    image: "/images/shuvo.jpg",
    bio: "২ বছর শিক্ষকতার অভিজ্ঞতা",
  },
  {
    name: "নাহিন ইনতিশার",
    subject: "কম্পিউটার সায়েন্স এন্ড ইঞ্জিনিয়ারিং (CSE)",
    qualification: "ইউনাইটেড ইন্টারন্যাশনাল ইউনিভার্সিটি",
    image: "/images/nahin.jpg",
    bio: "১ বছর শিক্ষকতার অভিজ্ঞতা",
  },
  {
    name: "সাবরিনা আকতার রিমি",
    subject: "ভাষাবিজ্ঞান বিভাগ, কলা অনুষদ",
    qualification: "ঢাকা বিশ্ববিদ্যালয়",
    image: "/images/teachery.jpg",
    bio: "১ বছর শিক্ষকতার অভিজ্ঞতা",
  },
  {
    name: "আয়েশা খাতুন",
    subject: "পালি এন্ড বুদ্ধিস্ট স্টাডিজ, কলা অনুষদ",
    qualification: "ঢাকা বিশ্ববিদ্যালয়",
    image: "/images/teachery.jpg",
    bio: "১ বছর শিক্ষকতার অভিজ্ঞতা",
  },
];
